apiVersion: v1
kind: Service
metadata:
  name: mernsample-service
spec:
  type: NodePort
  selector:
    app: mernsample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
